# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
from osv import fields,osv

class hr_employee(osv.osv):
        _inherit = 'hr.employee'
        _columns = {
                'loan':fields.one2many('hr.employee.loan','employee_id','Prets'),
        }
hr_employee()


class hr_employee_loan(osv.osv):
    """(NULL)"""
    _name = 'hr.employee.loan'
    _columns = {
        'name': fields.many2one('res.bank','Banque', help='Banque'),
        'date_start': fields.date('Date Debut', help='Date debut du pret'),
        'date_end': fields.date('Date Fin', help='Date Fin'),
	'employee_id':fields.many2one('hr.employee','Pret'),
    }
hr_employee_loan()

#class hr_payroll_ma(osv.osv):
#	_inherit='hr.payroll.ma'
#	_columns ={
#		'date_transfer':fields.date('Date de Transfert Bancaire'),
#		'bank_id':fields.many2one('res.partner.bank','Banque de transfert')
#	}
#hr_payroll_ma()
