# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
from osv import fields,osv

class hr_employee(osv.osv):
        _inherit = 'hr.employee'
        _columns = {
                'sanction_ids':fields.one2many('hr.employee.sanction','name','Sanctions'),
                'qualification_ids':fields.one2many('hr.employee.qualification','employee_id','Qualifications'),
                'medical_ids':fields.one2many('hr.employee.medical.ticket','employee_id','Billet Medical'),


        }
hr_employee()

class sanction_type(osv.osv):
        _name = 'sanction.type'
        _columns = {
                'name':fields.char('Description',size=32),
        }
sanction_type()

class qual_type(osv.osv):
        _name = 'qual.type'
        _columns = {
                'name':fields.char('Description',size=32),
        }
qual_type()

class medical_type(osv.osv):
        _name = 'medical.type'
        _columns = {
                'name':fields.char('Description',size=32),
        }
medical_type()


class hr_employee_sanction(osv.osv):
    """gestion des sanctions"""
    _name = 'hr.employee.sanction'
    _columns = {
        'motif': fields.char('Motif',size=64),
        'date': fields.date('Date'),
        'name': fields.many2one('hr.employee','Salarie'),
	'type':fields.many2one('sanction.type','Type de Sanction')
    }
hr_employee_sanction()

class hr_employee_qualification(osv.osv):
    """gestion des qualifications"""
    _name = 'hr.employee.qualification'
    _columns = {
        'date': fields.date('Date'),
        'name': fields.many2one('qual.type','Qualification'),
        'employee_id':fields.many2one('hr.employee','Salarie')
    }
hr_employee_qualification()

class hr_employee_medical_ticket(osv.osv):
    """gestion des ticket medical"""
    _name = 'hr.employee.medical.ticket'
    _columns = {
        'date': fields.date('Date'),
        'name': fields.many2one('medical.type','Medical'),
        'employee_id':fields.many2one('hr.employee','Salarie')
    }
hr_employee_medical_ticket()

